on:
  pull_request:
    branches: 
      - main
jobs:
  merge-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Merge PR
        id: merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge --auto --delete-branch --squash "$BRANCH_NAME"

